FROM node:15

WORKDIR /var/www

ADD ./package.json package.json
ADD ./gulpfile.js gulpfile.js
#ADD ./dev/server.js dev/server.js
RUN npm install
RUN npm install gulp --global


#CMD ["node","dev/server.js"]
CMD ["gulp","dev"]
